-- ROOM INSERT
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));
INSERT INTO room(room_number) VALUES(nextval('room_number'));

-- ELDER INSERT
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Benni', 'Blaydon', '1/8/1938', 'Female', 1);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Wilone', 'O''Rodane', '10/29/1949', 'Female', 2);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Margit', 'Dizlie', '2/9/1930', 'Female', 3);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Norry', 'Simons', '1/1/1950', 'Male', 4);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Jarrad', 'Sharer', '9/10/1934', 'Male', 5);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Janot', 'Maitland', '7/14/1950', 'Female', 6);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Rudyard', 'Greenier', '7/31/1948', 'Male', 7);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Orelia', 'Tyrwhitt', '8/2/1945', 'Female', 8);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Ode', 'Dreinan', '6/17/1941', 'Male', 9);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Zelig', 'Reinbech', '7/25/1934', 'Male', 10);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Olivier', 'Stuttard', '12/14/1940', 'Male', 11);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Clemens', 'Winthrop', '1/3/1951', 'Male', 12);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Reamonn', 'Dagless', '9/8/1931', 'Male', 13);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Janek', 'MacDermot', '6/12/1937', 'Male', 14);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Conrade', 'Bennetto', '2/17/1931', 'Male', 15);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Tomasina', 'Haggata', '4/10/1944', 'Female', 16);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Katusha', 'Misselbrook', '2/12/1937', 'Female', 17);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Colly', 'Humes', '11/15/1942', 'Female', 18);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Leo', 'Lashley', '6/3/1945', 'Male', 19);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Mabelle', 'Tringham', '3/26/1935', 'Female', 20);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Gae', 'Figliovanni', '8/28/1930', 'Female', 21);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Barny', 'Chittenden', '6/5/1939', 'Male', 22);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Antonio', 'Varnals', '11/14/1943', 'Male', 23);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Berkly', 'De Brett', '11/15/1936', 'Male', 24);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Chip', 'Cossum', '6/17/1942', 'Male', 25);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Vivianne', 'Faldoe', '11/3/1952', 'Female', 26);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Wayne', 'Muriel', '5/17/1954', 'Male', 27);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Brnaby', 'Jiggle', '4/19/1941', 'Male', 28);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Von', 'Cowp', '3/25/1939', 'Male', 29);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Waylin', 'de Nore', '1/20/1940', 'Male', 30);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Jaimie', 'Adamou', '9/22/1952', 'Male', 31);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Haily', 'Spurnier', '12/21/1937', 'Female', 32);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Britta', 'Vondra', '1/17/1930', 'Female', 33);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Muriel', 'Franciskiewicz', '8/12/1953', 'Female', 34);
insert into elder (first_name, last_name, date_of_birth, gender, number_of_room) values ('Christophorus', 'O'' Timony', '2/14/1954', 'Male', 35);


-- VISITOR INSERT
insert into visitor (id,first_name, last_name) values (-1,'NULL', 'NULL');

insert into visitor (first_name, last_name) values ('Collette', 'Tuerena');
insert into visitor (first_name, last_name) values ('Dale', 'Barfoot');
insert into visitor (first_name, last_name) values ('Efrem', 'Cheetham');
insert into visitor (first_name, last_name) values ('Celle', 'De Marchi');
insert into visitor (first_name, last_name) values ('Tymon', 'Skipper');
insert into visitor (first_name, last_name) values ('Vin', 'Fardy');
insert into visitor (first_name, last_name) values ('Marlie', 'Mc Carrick');
insert into visitor (first_name, last_name) values ('Eberhard', 'Burnes');
insert into visitor (first_name, last_name) values ('Cris', 'Riall');
insert into visitor (first_name, last_name) values ('Kahlil', 'Chippindale');
insert into visitor (first_name, last_name) values ('Murdoch', 'Nassi');
insert into visitor (first_name, last_name) values ('Onfre', 'Ducroe');
insert into visitor (first_name, last_name) values ('Anitra', 'Lambrick');
insert into visitor (first_name, last_name) values ('Averill', 'Bresnahan');
insert into visitor (first_name, last_name) values ('Marget', 'Cicculi');
insert into visitor (first_name, last_name) values ('Merlina', 'Fielden');
insert into visitor (first_name, last_name) values ('Ashleigh', 'Creus');
insert into visitor (first_name, last_name) values ('Christos', 'McCreath');
insert into visitor (first_name, last_name) values ('Kenny', 'Ughetti');
insert into visitor (first_name, last_name) values ('Dagmar', 'Senchenko');
insert into visitor (first_name, last_name) values ('Fraser', 'Utting');
insert into visitor (first_name, last_name) values ('Laraine', 'Blacksell');
insert into visitor (first_name, last_name) values ('Merv', 'Antushev');
insert into visitor (first_name, last_name) values ('Perry', 'Bedenham');
insert into visitor (first_name, last_name) values ('Garrek', 'Stubbings');
insert into visitor (first_name, last_name) values ('Joycelin', 'Jewks');
insert into visitor (first_name, last_name) values ('Minne', 'Loughnan');
insert into visitor (first_name, last_name) values ('Maryrose', 'Rearden');
insert into visitor (first_name, last_name) values ('Catharina', 'Slainey');
insert into visitor (first_name, last_name) values ('Robinet', 'Marusyak');
insert into visitor (first_name, last_name) values ('Jared', 'Kingsly');
insert into visitor (first_name, last_name) values ('Yehudit', 'D''Costa');
insert into visitor (first_name, last_name) values ('Allys', 'Float');
insert into visitor (first_name, last_name) values ('Paul', 'Boule');
insert into visitor (first_name, last_name) values ('Chariot', 'Matejic');
insert into visitor (first_name, last_name) values ('Denny', 'Coleborn');
insert into visitor (first_name, last_name) values ('Florenza', 'Pratty');
insert into visitor (first_name, last_name) values ('Valeda', 'Hinchshaw');
insert into visitor (first_name, last_name) values ('Claresta', 'Tregenna');
insert into visitor (first_name, last_name) values ('Aloysius', 'O''Moylan');
insert into visitor (first_name, last_name) values ('Coralie', 'Hebard');
insert into visitor (first_name, last_name) values ('Osbert', 'Walak');
insert into visitor (first_name, last_name) values ('Emilee', 'Sambrook');
insert into visitor (first_name, last_name) values ('Auguste', 'Le Cornu');
insert into visitor (first_name, last_name) values ('Sascha', 'Klaesson');
insert into visitor (first_name, last_name) values ('Adria', 'Cocke');
insert into visitor (first_name, last_name) values ('Blayne', 'Gudgion');
insert into visitor (first_name, last_name) values ('Edi', 'Kersley');
insert into visitor (first_name, last_name) values ('Gradeigh', 'Van Dijk');
insert into visitor (first_name, last_name) values ('Claudian', 'Tomik');
insert into visitor (first_name, last_name) values ('Viviana', 'Coffey');
insert into visitor (first_name, last_name) values ('Torry', 'Caig');
insert into visitor (first_name, last_name) values ('Jeddy', 'Eastbrook');
insert into visitor (first_name, last_name) values ('Grata', 'Pinder');
insert into visitor (first_name, last_name) values ('Robert', 'Scoterbosh');
insert into visitor (first_name, last_name) values ('Bettye', 'Hartington');
insert into visitor (first_name, last_name) values ('Lanny', 'Langsbury');
insert into visitor (first_name, last_name) values ('Theresina', 'MacConnulty');
insert into visitor (first_name, last_name) values ('Kippy', 'Westman');
insert into visitor (first_name, last_name) values ('Padget', 'Harwick');
insert into visitor (first_name, last_name) values ('Sutton', 'Steventon');
insert into visitor (first_name, last_name) values ('Ward', 'Goldring');
insert into visitor (first_name, last_name) values ('Sherm', 'Bearfoot');
insert into visitor (first_name, last_name) values ('Aida', 'Clemenzo');
insert into visitor (first_name, last_name) values ('Reggie', 'Barnhart');
insert into visitor (first_name, last_name) values ('Kathleen', 'Rowe');
insert into visitor (first_name, last_name) values ('Curran', 'Scobie');
insert into visitor (first_name, last_name) values ('Hayward', 'Ketts');
insert into visitor (first_name, last_name) values ('Elle', 'De''Ath');
insert into visitor (first_name, last_name) values ('Ingelbert', 'Stelle');
insert into visitor (first_name, last_name) values ('Noel', 'Reiling');
insert into visitor (first_name, last_name) values ('Catherin', 'Brittain');
insert into visitor (first_name, last_name) values ('Nelia', 'Fitchew');
insert into visitor (first_name, last_name) values ('Giffy', 'Simpkiss');
insert into visitor (first_name, last_name) values ('Lucais', 'Dawidowicz');
insert into visitor (first_name, last_name) values ('Claybourne', 'Browse');
insert into visitor (first_name, last_name) values ('Drucy', 'Dederich');
insert into visitor (first_name, last_name) values ('Humbert', 'Tunstall');
insert into visitor (first_name, last_name) values ('Dosi', 'Kyberd');
insert into visitor (first_name, last_name) values ('Falito', 'Ivankovic');
insert into visitor (first_name, last_name) values ('Aida', 'Snelgrove');
insert into visitor (first_name, last_name) values ('Blayne', 'Watkinson');
insert into visitor (first_name, last_name) values ('Amitie', 'Bilovsky');
insert into visitor (first_name, last_name) values ('Ardelis', 'Dacca');
insert into visitor (first_name, last_name) values ('Corrine', 'Brownell');
insert into visitor (first_name, last_name) values ('Neysa', 'Kretschmer');
insert into visitor (first_name, last_name) values ('Stacia', 'Borrill');
insert into visitor (first_name, last_name) values ('Mervin', 'Wilkins');
insert into visitor (first_name, last_name) values ('Kaylyn', 'Capnor');
insert into visitor (first_name, last_name) values ('Georgette', 'Salman');
insert into visitor (first_name, last_name) values ('Arlette', 'Rushworth');
insert into visitor (first_name, last_name) values ('Sheilah', 'Wearing');
insert into visitor (first_name, last_name) values ('Korry', 'Chasmer');
insert into visitor (first_name, last_name) values ('Nadiya', 'Feore');
insert into visitor (first_name, last_name) values ('Cloris', 'Jacobi');
insert into visitor (first_name, last_name) values ('Pete', 'Rigden');
insert into visitor (first_name, last_name) values ('Maddy', 'Rabbitt');
insert into visitor (first_name, last_name) values ('Lilith', 'Rayson');
insert into visitor (first_name, last_name) values ('Felicity', 'Mackerness');
insert into visitor (first_name, last_name) values ('Antonina', 'Fieldstone');
insert into visitor (first_name, last_name) values ('Sydney', 'Gentzsch');
insert into visitor (first_name, last_name) values ('Sophia', 'Hollow');
insert into visitor (first_name, last_name) values ('Byram', 'Albon');
insert into visitor (first_name, last_name) values ('Sara', 'Bretherton');
insert into visitor (first_name, last_name) values ('Nona', 'Arnatt');
insert into visitor (first_name, last_name) values ('Terrill', 'Blewmen');
insert into visitor (first_name, last_name) values ('Gallagher', 'Yakunkin');
insert into visitor (first_name, last_name) values ('Tyne', 'Vaggers');
insert into visitor (first_name, last_name) values ('Ola', 'Camerati');
insert into visitor (first_name, last_name) values ('Fields', 'Speek');
insert into visitor (first_name, last_name) values ('Sharon', 'Smail');
insert into visitor (first_name, last_name) values ('Georgetta', 'Schiell');
insert into visitor (first_name, last_name) values ('Iggy', 'Woofenden');
insert into visitor (first_name, last_name) values ('Mair', 'Stainer');
insert into visitor (first_name, last_name) values ('Paco', 'Kiddey');
insert into visitor (first_name, last_name) values ('Andonis', 'McCreadie');
insert into visitor (first_name, last_name) values ('Gilles', 'Klimochkin');
insert into visitor (first_name, last_name) values ('Carey', 'Caban');
insert into visitor (first_name, last_name) values ('Chryste', 'Dymond');
insert into visitor (first_name, last_name) values ('Lisabeth', 'Scrace');
insert into visitor (first_name, last_name) values ('Aylmar', 'Cossons');
insert into visitor (first_name, last_name) values ('Clareta', 'Wimes');
insert into visitor (first_name, last_name) values ('Lavena', 'Mowen');
insert into visitor (first_name, last_name) values ('Fidel', 'Harrie');
insert into visitor (first_name, last_name) values ('Jayme', 'Lardner');
insert into visitor (first_name, last_name) values ('Caresa', 'Trousdale');
insert into visitor (first_name, last_name) values ('Sampson', 'Verillo');
insert into visitor (first_name, last_name) values ('Lonnard', 'Jakel');
insert into visitor (first_name, last_name) values ('Hartley', 'Dowtry');
insert into visitor (first_name, last_name) values ('Jeramie', 'Roll');
insert into visitor (first_name, last_name) values ('Stillmann', 'Prynne');
insert into visitor (first_name, last_name) values ('Frasquito', 'Lohden');
insert into visitor (first_name, last_name) values ('Aveline', 'Pre');
insert into visitor (first_name, last_name) values ('Hale', 'Gott');
insert into visitor (first_name, last_name) values ('Fina', 'Gerry');
insert into visitor (first_name, last_name) values ('Dieter', 'Rothermel');
insert into visitor (first_name, last_name) values ('Kendall', 'Dungey');
insert into visitor (first_name, last_name) values ('Lionello', 'Toseland');
insert into visitor (first_name, last_name) values ('Noellyn', 'Deme');
insert into visitor (first_name, last_name) values ('Tremayne', 'Jeff');
insert into visitor (first_name, last_name) values ('Dorella', 'Barrus');
insert into visitor (first_name, last_name) values ('Ashley', 'Pocklington');
insert into visitor (first_name, last_name) values ('Sada', 'Tyas');
insert into visitor (first_name, last_name) values ('Jerad', 'Easum');
insert into visitor (first_name, last_name) values ('Rosaline', 'Dagwell');
insert into visitor (first_name, last_name) values ('Bernita', 'Roust');
insert into visitor (first_name, last_name) values ('Dorolisa', 'Blazey');
insert into visitor (first_name, last_name) values ('Leola', 'O''Duggan');
insert into visitor (first_name, last_name) values ('Nickie', 'Gwyneth');
insert into visitor (first_name, last_name) values ('Xymenes', 'Mellows');
insert into visitor (first_name, last_name) values ('Merry', 'Loody');
insert into visitor (first_name, last_name) values ('Morey', 'Boriston');
insert into visitor (first_name, last_name) values ('Hamilton', 'Dachey');
insert into visitor (first_name, last_name) values ('Misty', 'Windle');
insert into visitor (first_name, last_name) values ('Fransisco', 'Stork');
insert into visitor (first_name, last_name) values ('Shantee', 'Frend');
insert into visitor (first_name, last_name) values ('Marcelia', 'Karel');
insert into visitor (first_name, last_name) values ('Caryl', 'Zupone');
insert into visitor (first_name, last_name) values ('Faydra', 'Jowling');
insert into visitor (first_name, last_name) values ('Martino', 'Bortolazzi');
insert into visitor (first_name, last_name) values ('Lucias', 'Dulake');
insert into visitor (first_name, last_name) values ('Celestia', 'Kubicka');
insert into visitor (first_name, last_name) values ('Lacie', 'Odeson');
insert into visitor (first_name, last_name) values ('Clement', 'Pischof');
insert into visitor (first_name, last_name) values ('Nonnah', 'Norssister');
insert into visitor (first_name, last_name) values ('Eleonore', 'Ditch');
insert into visitor (first_name, last_name) values ('Albina', 'Bardwall');
insert into visitor (first_name, last_name) values ('Ulrick', 'Wimmers');
insert into visitor (first_name, last_name) values ('Meridel', 'Blomefield');
insert into visitor (first_name, last_name) values ('Ole', 'Eighteen');
insert into visitor (first_name, last_name) values ('Ulick', 'Christofe');
insert into visitor (first_name, last_name) values ('Hildy', 'Milier');
insert into visitor (first_name, last_name) values ('Michaeline', 'Kellie');
insert into visitor (first_name, last_name) values ('Angela', 'Waggitt');
insert into visitor (first_name, last_name) values ('Geoff', 'Moyles');
insert into visitor (first_name, last_name) values ('Jolee', 'Havesides');
insert into visitor (first_name, last_name) values ('Ash', 'Doggerell');
insert into visitor (first_name, last_name) values ('Artur', 'Prewer');
insert into visitor (first_name, last_name) values ('Charita', 'Yitzhakov');
insert into visitor (first_name, last_name) values ('Xylina', 'Lynett');
insert into visitor (first_name, last_name) values ('Ruthi', 'Woolpert');
insert into visitor (first_name, last_name) values ('Callean', 'Barnicott');
insert into visitor (first_name, last_name) values ('Carolus', 'Goodluck');
insert into visitor (first_name, last_name) values ('Eileen', 'Bereford');
insert into visitor (first_name, last_name) values ('Goran', 'Perone');
insert into visitor (first_name, last_name) values ('Miof mela', 'Tills');
insert into visitor (first_name, last_name) values ('Major', 'McCartan');
insert into visitor (first_name, last_name) values ('Ariella', 'Swetman');
insert into visitor (first_name, last_name) values ('Loleta', 'Jovicevic');
insert into visitor (first_name, last_name) values ('Meggi', 'Deary');
insert into visitor (first_name, last_name) values ('April', 'Dumphries');
insert into visitor (first_name, last_name) values ('Meade', 'Bedenham');
insert into visitor (first_name, last_name) values ('Rosita', 'Pedican');
insert into visitor (first_name, last_name) values ('Graeme', 'Syce');
insert into visitor (first_name, last_name) values ('Karin', 'Clapshaw');
insert into visitor (first_name, last_name) values ('Prince', 'Lumm');
insert into visitor (first_name, last_name) values ('Grady', 'Barbrook');
insert into visitor (first_name, last_name) values ('Gregorio', 'Staterfield');
insert into visitor (first_name, last_name) values ('Augustine', 'Upham');
insert into visitor (first_name, last_name) values ('Ralina', 'Balston');


-- EMPLOYEE FEMALE INSERT
insert into employee (first_name, last_name, gender) values ('Simonne', 'St. Quintin', 'Female');
insert into employee (first_name, last_name, gender) values ('Melita', 'Tubble', 'Female');
insert into employee (first_name, last_name, gender) values ('Estel', 'Jahnel', 'Female');
insert into employee (first_name, last_name, gender) values ('Berenice', 'Reitenbach', 'Female');
insert into employee (first_name, last_name, gender) values ('Brigid', 'Markie', 'Female');
insert into employee (first_name, last_name, gender) values ('Leelah', 'Delahunt', 'Female');
insert into employee (first_name, last_name, gender) values ('Izabel', 'Yashaev', 'Female');
insert into employee (first_name, last_name, gender) values ('Blinny', 'Cherryman', 'Female');
insert into employee (first_name, last_name, gender) values ('Crissie', 'Dillinton', 'Female');
insert into employee (first_name, last_name, gender) values ('Annmarie', 'Glossop', 'Female');

-- EMPLOYEE MALE INSERT
insert into employee (first_name, last_name, gender) values ('Tanny', 'Feldberg', 'Male');
insert into employee (first_name, last_name, gender) values ('Obie', 'Saile', 'Male');
insert into employee (first_name, last_name, gender) values ('King', 'Peers', 'Male');
insert into employee (first_name, last_name, gender) values ('Timoteo', 'Pittle', 'Male');
insert into employee (first_name, last_name, gender) values ('Rik', 'Willets', 'Male');
insert into employee (first_name, last_name, gender) values ('Richardo', 'Camel', 'Male');
insert into employee (first_name, last_name, gender) values ('Samuele', 'Herity', 'Male');
insert into employee (first_name, last_name, gender) values ('Francklin', 'Sterrie', 'Male');
insert into employee (first_name, last_name, gender) values ('Orion', 'Hewes', 'Male');
insert into employee (first_name, last_name, gender) values ('Isiahi', 'Kilbourne', 'Male');

-- VISITS

insert into visit (first_visitor_id, second_visitor_id, elder_id) values (119, 71, 25);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (32, 15, 27);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (105, -1, 16);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (175, 75, 33);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (69, 68, 15);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (124, 131, 19);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (104, -1, 16);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (145, 72, 4);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (180, 36, 9);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (16, 87, 1);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (117, 184, 11);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (86, 88, 26);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (85, 26, 13);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (82, -1, 8);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (69, 163, 14);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (197, 113, 27);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (35, 161, 25);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (85, 34, 31);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (198, 135, 35);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (136, 158, 25);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (89, 69, 12);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (13, 148, 23);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (146, 43, 26);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (24, -1, 6);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (12, -1, 4);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (147, -1, 20);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (7, 41, 26);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (139, -1, 15);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (185, 174, 27);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (25, 141, 15);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (16, -1, 10);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (63, 125, 23);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (12, 51, 16);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (116, 38, 3);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (28, -1, 20);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (107, -1, 4);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (100, 22, 23);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (191, 172, 3);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (24, 158, 26);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (144, 78, 3);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (33, -1, 31);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (34, -1, 8);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (134, 165, 18);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (109, -1, 25);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (35, -1, 12);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (195, 174, 21);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (69, 84, 33);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (80, 40, 35);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (38, 44, 20);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (23, 67, 14);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (89, 178, 28);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (30, 131, 20);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (100, 126, 19);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (78, 68, 24);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (149, 185, 27);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (114, 54, 14);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (10, -1, 5);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (7, 78, 29);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (85, -1, 23);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (21, 97, 13);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (54, 81, 8);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (31, 5, 6);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (130, 115, 17);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (185, -1, 34);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (14, 4, 29);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (54, -1, 12);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (53, 91, 18);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (103, -1, 7);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (143, 120, 19);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (124, 148, 21);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (49, 41, 25);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (52, 28, 19);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (143, 157, 2);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (37, -1, 34);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (27, -1, 29);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (151, 131, 18);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (164, 51, 9);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (141, 178, 17);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (1, 88, 11);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (47, -1, 1);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (63, 7, 12);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (26, 154, 1);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (99, 47, 18);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (31, 66, 3);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (18, 65, 26);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (35, -1, 22);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (8, 13, 27);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (94, 141, 15);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (55, -1, 12);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (153, 12, 22);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (54, 160, 15);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (28, 197, 28);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (37, 37, 3);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (25, 7, 17);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (126, 140, 29);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (63, 159, 14);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (196, 49, 13);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (111, 188, 21);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (85, 114, 24);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (9, 94, 24);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (126, -1, 12);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (147, 31, 7);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (154, -1, 4);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (109, -1, 21);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (86, 160, 8);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (141, 26, 17);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (178, -1, 12);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (44, 39, 7);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (24, 112, 27);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (109, 192, 20);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (25, 2, 6);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (104, 5, 22);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (175, 144, 1);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (11, 71, 4);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (58, 32, 2);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (41, 27, 8);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (147, -1, 32);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (14, -1, 34);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (165, -1, 31);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (161, 178, 33);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (180, 195, 16);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (116, 81, 6);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (42, 57, 34);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (36, -1, 11);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (17, -1, 4);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (15, 5, 34);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (40, 134, 21);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (168, 100, 4);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (86, 20, 8);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (6, 142, 28);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (1, 118, 34);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (14, 53, 8);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (9, 127, 4);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (151, 6, 7);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (193, 84, 26);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (177, 138, 21);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (190, 125, 32);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (97, -1, 19);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (157, 101, 28);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (90, 170, 23);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (176, 173, 20);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (146, 38, 27);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (197, -1, 21);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (53, 30, 25);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (14, -1, 23);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (40, 33, 2);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (120, 161, 27);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (99, 103, 11);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (121, 145, 2);
insert into visit (first_visitor_id, second_visitor_id, elder_id) values (185, -1, 11);
